root: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  requireConfigFile: false
env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
plugins:
  - prettier
rules:
  id-length: off
  class-methods-use-this:
    - error
    - exceptMethods:
      # These methods are often overridden to hide implementation
      # in parent class and throw error on invokation.
      - field
      - script
      - missing
      - format
      - gapPolicy
      - validationMethod
      - scoreMode
      - value
      - executionHint
      - _warn
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  no-console: off
  prefer-const: error
  no-var: error
  no-irregular-whitespace:
    - error
    - skipComments: true
