language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

node_js:
  - '8'
  - '6'
  - '4'

cache: yarn

before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: yarn run check

# Only the node version 8 job will upload the lockfile
after_script:
  - greenkeeper-lockfile-upload
  - yarn run coverage

after_success:
  - yarn global add travis-deploy-once
  - travis-deploy-once "yarn global add semantic-release@12 && semantic-release"
